name: 🦍 Generate Donkey Kong GitHub Contributions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate-grid:
    runs-on: ubuntu-latest
    name: Generate animated grid
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate SVG
        uses: Platane/snk@v3
        with:
          github_user_name: heubert-69
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
